trigger:
  - main

pool:
  name: Default # O el nombre de tu pool de agentes
  demands:
    - agent.name -equals agent-laptop-1

steps:
  - task: UseNode@1
    inputs:
      version: "18.x"

  - script: |
      npm install
    displayName: "Instalar dependencias"

  - script: |
      npm run lint
    displayName: "Ejecutar ESLint"

  - script: |
      npm test
    displayName: "Ejecutar Pruebas Unitarias"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students(b1a9be0c-3adb-4b54-9b44-14b4d64810e1)'
      appType: 'webAppLinux'
      appName: 'devops'
      package: '$(Build.ArtifactStagingDirectory)/*.zip'
      runtimeStack: 'NODE|18-lts'
      startUpCommand: 'npm start'
